"""
Django settings for nl_restreamer project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import socket
import boto3
from pathlib import Path
from dotenv import load_dotenv
from linode_api4 import Instance, LinodeClient, objects

env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from decouple import config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
ALLOWED_HOSTS = ['*'] + ips

INSTALLED_APPS = [
    "nl_restreamer.apps.MyAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    'daphne',
    "django.contrib.staticfiles",
    "restreamer.apps.RestreamerConfig",
    "admin_object_actions",
    "rest_framework",
    "accounts.apps.AccountsConfig",
    'crispy_forms',
    'crispy_bootstrap5',
    'channels',
    'simple_history',

]


CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "crum.CurrentRequestUserMiddleware",
    'simple_history.middleware.HistoryRequestMiddleware'
]

ROOT_URLCONF = "nl_restreamer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'restreamer', 'templates'),
                 os.path.join(BASE_DIR, 'accounts', 'templates'),
                ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nl_restreamer.wsgi.application"
ASGI_APPLICATION = 'nl_restreamer.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "restreamer-manager",
        "USER": "manager-admin",
        "PASSWORD": "Grwz2180",
        "HOST": "localhost",
        "PORT": "5432",
    },
    "client_db": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Bratislava"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "restreamer",  "static/")


LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/control/home/'

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname}|{filename}:{lineno}|{message}",
            "style": "{",
        },
        "format_with_thread": {
            "format": "{asctime} {levelname}|{processName}|{filename}:{lineno}|{message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "console_with_thread": {
            "class": "logging.StreamHandler",
            "formatter": "format_with_thread",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR / "endpoint_service.log"),
            "formatter": "format_with_thread",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },
        "restreamer": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
        },
        "restreamer.endpoints": {
            "handlers": ["console_with_thread"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 30000

AUTH_USER_MODEL = 'accounts.RestreamerUser'

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = ["https://restreamer.solarnyexprex.eu"]


AWS_STORAGE_BUCKET_NAME = 'linode52'
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
OBJECT_STORAGE_URL = 'https://eu-central-1.linodeobjects.com'

S3_CLIENT = boto3.client('s3',
                         endpoint_url=OBJECT_STORAGE_URL,
                         aws_access_key_id=AWS_ACCESS_KEY_ID,
                         aws_secret_access_key=AWS_SECRET_ACCESS_KEY)


token = os.getenv('LINODE_TOKEN')
LINODE_CLIENT = LinodeClient(token)
INSTANCE_TYPE_4G = os.getenv('INSTANCE_TYPE_4G')
INSTANCE_TYPE_8G = os.getenv('INSTANCE_TYPE_8G')
REGION = os.getenv('INSTANCE_REGION')
ROOT_PASSWORD = os.getenv('ROOT_SERVER_PASSWORD')


CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True